### PR TITLE
Show @stellar/anchor-tests version on UI

### PR DESCRIPTION
**Pull request by quietbits**
I had to create `/src` level `tsconfig` to import `package.json` file. I didn't see any issues, so hopefully, nothing broke. :crossed_fingers: 

image

### CODE REVIEW

**Comment by Ifropc** [comment]
@quietbits PR preview failed for some reason, could you check? 
Other than that LGTM

**Comment by quietbits** [comment]
@Ifropc PR preview is fixed. It didn't work with the workspace, so we need to install `@stellar/anchor-tests` package for the `ui`. It's also cleaner to use the local `ui` `package.json` file to get the package version.

**Comment by Ifropc** [comment]
@quietbits can we request version of the library from the server? 
Potentially, versions on UI and server could mismatch

**Review by piyalbasu — APPROVED** [review]

**Comment by Ifropc** [comment]
Looks great, tysm!

**Pull request merged**
